<?php

namespace Esprit\GameHubBundle\Repository;

/**
 * JeuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JeuRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllOrderedByName($title)
    {
        return $this->getEntityManager()
            ->createQuery(
            //       'SELECT p FROM KarhabtyAnnonceBundle:Annonce p ORDER BY p.Model ASC'
            // )
            // ->getResult();

                "SELECT p
                      FROM whysawBundle:jeu p
                           WHERE 
                                   p.nom LIKE :nom 
                                   "

            )->setParameter('nom', '%' . $title . '%')



            ->getResult();
    }


}
