<?php
/**
 * Created by PhpStorm.
 * User: Administrateur
 * Date: 27/03/2017
 * Time: 10:47
 */

namespace Administration\AdminBundle\Controller;

use Esprit\GameHubBundle\Entity\JeuAmateur;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Esprit\GameHubBundle\Controller\JeuAmateurController;
use Symfony\Component\HttpFoundation\Request;

class AdminJAController extends JeuAmateurController
{
    public function indexAction(Request $request)
    {
        return parent::indexAction($request);
    }

    public function newAction(Request $request)
    {
        return parent::newAction($request); // TODO: Change the autogenerated stub
    }

    public function showAction(JeuAmateur $jeuAmateur)
    {
        return parent::showAction($jeuAmateur); // TODO: Change the autogenerated stub
    }

    public function editAction(Request $request, JeuAmateur $jeuAmateur)
    {
        return parent::editAction($request, $jeuAmateur); // TODO: Change the autogenerated stub
    }


}