jeu_index:
    path:     /
    defaults: { _controller: "EspritGameHubBundle:Jeu:index" }
    methods:  GET


jeu_show:
    path:     /{id}/show
    defaults: { _controller: "EspritGameHubBundle:Jeu:show" }
    methods:  GET

jeu_new:
    path:     /new
    defaults: { _controller: "EspritGameHubBundle:Jeu:new" }
    methods:  [GET, POST]

jeu_edit:
    path:     /{id}/edit
    defaults: { _controller: "EspritGameHubBundle:Jeu:edit" }
    methods:  [GET, POST]

jeu_delete:
    path:     /{id}/delete
    defaults: { _controller: "EspritGameHubBundle:Jeu:delete" }
    methods:  DELETE
